CFLAGS=-Wall -g -DNDEBUG

objects = ex1 ex3 ex5 ex6 ex7 ex8 ex9 ex10 ex11 ex12 ex13 ex14 ex15 ex16 ex17 ex18 ex19 ex20 ex22_main ex23 ex24 ex25 ex26

.PHONY:all
all:$(objects)

ex19:object.o

ex22_main:ex22.o

.PHONY:clean
clean:
	-rm $(objects) *.o
