[package]
name = "rs-burn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
burn = { version = "0.11", features = ["train", "wgpu"] }
gix-fs = "0.11"
serde = "1"
time = "0.3.36"
