version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Asia/Shanghai
      # This claim code will expire in 4 minutes
      - PLEX_CLAIM=claim-m5Qxes3EvL9zHP71dYNy
      - ADVERTISE_IP=http://192.168.3.3:32400/
      - PLEX_UID=1000
      - PLEX_GID=1000
      - ALLOWED_NETWORKS=192.168.3.0/24
    hostname: plex
    volumes:
      - ./plex_config:/config
      - ./plex_transcode:/transcode
      - /webdav:/data
