default: test

alias s := search
search crate:
    cargo search --registry crates-io {{crate}}

alias c := check
check:
    cargo check
    cargo fmt
    cargo clippy --all -- -D warnings

alias t := test
test:
    cargo test

clean:
    cargo clean
