[package]
name = "sokoban-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ggez = "0.7"
specs ={ version = "0.17.0", features = ["specs-derive"]}
glam = { version = "0.20.0", features = ["mint"] }
itertools = "0.9.0"
