[package]
name = "sokoban-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ggez = "0.9"
specs ={ version = "0.20", features = ["specs-derive"]}
glam = { version = "0.29", features = ["mint"] }
itertools = "0.13"
