version: "2"

services:
  webdav:
    restart: always
    build: ./apache-webdav
    ports:
      - "80:80"
    volumes:
      - /webdav:/var/webdav
      - ./webdav-log:/var/log/apache2
    env_file: .env
